# Site settings
title: Chris Loftus
email: chrisloft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  jekyll ftw
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chrisloftus
github_username:  chrisloftus
